<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="artwa_robot">
    <!-- Material -->
    <material name="Red">
        <color rgba="1 0 0 1.0"/>
    </material>
    <material name="Green">
        <color rgba="0 1 0 1.0"/>
    </material>
    <material name="Blue">
        <color rgba="0 0 1 1.0"/>
    </material>
    <material name="White">
        <color rgba="1 1 1 1.0"/>
    </material>
    <material name="Black">
        <color rgba="0 0 0 1.0"/>
    </material>
    <material name="Gray">
        <color rgba="0.35 0.35 0.35 1.0"/>
    </material>

    
    <!-- Inertia Macros -->
    <xacro:macro name="box_inertia" params="mass length width height">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (height*height + width*width)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * mass * (length*length + height*height)}" iyz="0.0"
                     izz="${(1/12) * mass * (length*length + width*width)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="mass length radius">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                     izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>

    <!-- Properties -->
    <xacro:property name="full_body_length" value="1.466"/>
    <xacro:property name="full_body_width" value="0.725"/>
    <xacro:property name="full_body_height" value="0.5066"/>

    <xacro:property name="head_length" value="0.4"/>
    <xacro:property name="head_width" value="${full_body_width}"/>
    <xacro:property name="head_height" value="0.23"/>

    <xacro:property name="body_length" value="${full_body_length}"/>
    <xacro:property name="body_width" value="${full_body_width}"/>
    <xacro:property name="body_height" value="${full_body_height - head_height}"/>


    <xacro:property name="wheel_radius" value="0.1858"/>
    <xacro:property name="wheel_length" value="0.205"/>

    <xacro:property name="laser_radius" value="0.035"/>
    <xacro:property name="laser_length" value="0.04"/>

    <!-- Mass Properties -->
    <xacro:property name="body_mass" value="50.0"/>
    <xacro:property name="head_mass" value="20.0"/>
    <xacro:property name="wheel_mass" value="15.0"/>
    <xacro:property name="laser_mass" value="2.0"/>

    <!-- Links -->
    <link name="base_footprint"/>

    <link name="base_link"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" />
    </joint>

    <link name="body_link">
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <origin xyz="${body_length/2} 0.0 ${body_height/2}"/>
            <material name="Gray"/>
        </visual>
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <origin xyz="${body_length/2} 0.0 ${body_height/2}"/>
        </collision>
        <xacro:box_inertia mass="${body_mass}" length="${body_length}" width="${body_width}" height="${body_height}"/>
    </link>

    <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body_link"/>
        <origin xyz="-${body_length/2} 0 0" />
    </joint>

    <link name="head_link">
        <visual>
            <geometry>
                <box size="${head_length} ${head_width} ${head_height}"/>
            </geometry>
            <origin xyz="${head_length/2} 0.0 ${head_height/2}"/>
            <material name="Gray"/>
        </visual>
        <collision>
            <geometry>
                <box size="${head_length} ${head_width} ${head_height}"/>
            </geometry>
            <origin xyz="${head_length/2} 0.0 ${head_height/2}"/>
        </collision>
        <xacro:box_inertia mass="${head_mass}" length="${head_length}" width="${head_width}" height="${head_height}"/>
    </link>

    <joint name="head_joint" type="fixed">
        <parent link="body_link"/>
        <child link="head_link"/>
        <origin xyz="${full_body_length - head_length} 0.0 ${full_body_height - head_height}"/>
    </joint>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}"/>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 ${body_width/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}"/>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 -${body_width/2} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="laser_link">
        <visual>
            <geometry>
                <cylinder length="${laser_length}" radius="${laser_radius}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${laser_length/2}"/>
            <material name="Red"/>
        </visual>
        <xacro:cylinder_inertia mass="${laser_mass}" length="${laser_length}" radius="${laser_radius}"/>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="head_link"/>
        <child link="laser_link"/>
        <origin xyz="${head_length/2} 0.0 ${head_height}"/>
    </joint>

    <link name="laser"/>

    <joint name="real_laser_joint" type="fixed">
        <parent link="laser_link"/>
        <child link="laser"/>
        <origin xyz="0.0 0.0 -${full_body_height + wheel_radius}" rpy="0 0 ${pi}"/>
    </joint>
</robot>